### ISSUE TITLE
Arduino UNO R4

### ISSUE THREAD

**Issue by PeterUMJ** [mrrwa/LocoNet#39]
Are there any plans to support UNO R4?

//Peter

**Comment by kiwi64ajs** [comment]
I haven’t really thought about it. I guess so, but probably in the new LocoNet2 library, as I don’t want to keep adding layers and layers of patches to the LocoNet library.

I guess I should order some and have a play around with it.

Alex

**Comment by PeterUMJ** [comment]
Thanks for the reply, is there any timetable for LocoNet2?

Peter

**Comment by kiwi64ajs** [comment]
I’ve just ordered an Arduino UNO R4 to experiment with.

I had a quick read of the data sheet to see if it has any special UART status registers to make it easy to detect a busy LocoNet for the collision-sensing logic.

Alas, it doesn’t look like it has anything special/helpful, but hopefully, I can enable a Pin Change Interrupt on the RX Pin at the same time as receiving normal Serial Data via the UART, as I’ve done this with the RPI Pico RP2040 chip and it seems to work ok. If I can get the R4 to work like this then it shouldn’t take too much effort to support the R4… ;)

HTH

Alex

**Comment by PeterUMJ** [comment]
I hope you find an easy way to fix it
