### ISSUE TITLE
Typo in Sketch

### ISSUE THREAD

**Issue by gfgit** [mrrwa/LocoNet#9]
https://github.com/mrrwa/LocoNet/blob/374671990fd81905e85c96b39a983d8c604c3382/examples/LocoNetEtherBuffer/LocoNetEtherBuffer.ino#L68

https://github.com/mrrwa/LocoNet/blob/374671990fd81905e85c96b39a983d8c604c3382/examples/LocoNetEtherBuffer/LocoNetEtherBuffer.ino#L82

Should be LoconetOverTcp instead of LoconetOcerTcp

**Comment by kiwi64ajs** [comment]
Ok thanks, I've corrected this
